/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:d843ca93-d342-485c-986b-0a62409ff59f",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_rc8jc7ufB",
  aws_user_pools_web_client_id: "2ugdkc0ul0lvict4t82ghrlpf6",
  oauth: {},
  aws_appsync_graphqlEndpoint:
    "https://flpe2rua2fhonnrrjlo5znpegq.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-dssgdiqskfho7noq6nrk2r5h3q",
};

export default awsmobile;
